<html>
<head> Documento</head>
<body>
<table border="1">

    <tr>

    <td rowspan="3">
    <br><br><br><br>
<table border="1">

    <tr><td> Link para pagina 1 </td></tr>
    <tr><td> Link para pagina 2 </td></tr>
    <tr><td> Link para pagina 3 </td></tr>
    <tr><td> Link para pagina 4</td></tr>
</table>
<br><br><br><br>
</td>

<td><h1> TEXTO GRANDE </h1></td>
    </tr>
<tr>
    <td> <video src="200" height="100" controls>
        <source src="teste.mp4">
        </video></td>
</tr>
 
<tr><td><ul><l1>Item 1</l1>
               <li>Item 2</li>
                <li> Item 3</li>
</ul></td></tr>

</table>






</body>
</html>
